version: '3.8'
services:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - kafka
      - redis
      - mongodb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookstore
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/bookstore
      - OTHER_SERVICE_HOST=localhost

  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: Cheng1076
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "3181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis
    ports:
      - "6380:6379"

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: bookstore

volumes:
  mysql-data: